BancoEstadoBodega/Models/PRODUCTOBODEGA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTOBODEGA
    {
        public int PRODUCTO_IDProducto { get; set; }
        public int BODEGA_IDBodega { get; set; }
        public int Cajas { get; set; }
        public int Sueltas { get; set; }
    
        public virtual BODEGA BODEGA { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
    }
}

BancoEstadoBodega/Models/SolicitudPedido.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SolicitudPedido()
        {
            this.ProductosEnBodega = new HashSet<ProductosEnBodega>();
            this.ProductoSolicitud = new HashSet<ProductoSolicitud>();
        }
    
        public int idSolicitud { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idTipoEncomienda { get; set; }
        public Nullable<int> idTipoEmpaque { get; set; }
        public string origen { get; set; }
        public Nullable<int> idTipoDespacho { get; set; }
        public Nullable<int> idTrasladoDespacho { get; set; }
        public string destino { get; set; }
        public Nullable<System.DateTime> fechaSolicitud { get; set; }
        public Nullable<System.DateTime> fechaEntrega { get; set; }
        public string codigoSeguimiento { get; set; }
        public Nullable<int> idTipoPedido { get; set; }
        public Nullable<int> idArea { get; set; }
        public string usuarioMandante { get; set; }
        public string usuarioReceptor { get; set; }
        public Nullable<int> bultos { get; set; }
        public string observacion { get; set; }
        public Nullable<long> costeUnitario { get; set; }
        public Nullable<long> servicioMecanizado { get; set; }
        public Nullable<long> subtotal { get; set; }
        public string estado { get; set; }
        public string correo { get; set; }
        public Nullable<int> idMecanizado { get; set; }
        public Nullable<int> cod_estado { get; set; }
        public string urlPdf { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual estadoSolicitud estadoSolicitud { get; set; }
        public virtual Mecanizado Mecanizado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosEnBodega> ProductosEnBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoSolicitud> ProductoSolicitud { get; set; }
        public virtual TipoDespacho TipoDespacho { get; set; }
        public virtual TipoEmpaque TipoEmpaque { get; set; }
        public virtual TipoEncomienda TipoEncomienda { get; set; }
        public virtual TipoPedido TipoPedido { get; set; }
        public virtual TrasladoDespacho TrasladoDespacho { get; set; }
    }
}

BancoEstadoBodega/Models/SolicitudViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BancoEstadoBodega.Models;
using System.Web.Mvc;
using System.ComponentModel.DataAnnotations;



namespace BancoEstadoBodega.Models
{
    public class SolicitudViewModel
    {
        public SolicitudPedido solicitud { get; set; }
        public ProductosEnBodega bodega { get; set; }
        public List<SelectListItem> PRODUCTO { get; set; }
        public List<ProductosEnBodega> productosSeleccionados { get; set; }
        public List<ProductosEnBodega> productosSeleccionados2 { get; set; }
        public List<SelectListItem> UserSoloVista { get; set; }
        public List<SelectListItem> ProductosEnBodega { get; set; }
        public List<ProductoSolicitud> ProductoSolicitud2 { get; set; }
        public List<ProductoSolicitud> ProductoSolicitud3 { get; set; }
        public List<SelectListItem> ProductoSolicitud { get; set; }


        public String numeroOC { get; set; }
        public String detalleDestino { get; set; }

        public String Comprador { get; set; }

        public String Solicitante { get; set; }
        public String Observacion { get; set; }


        public IEnumerable<SelectListItem> Destinos
        {
            get
            {
                return new[]
                {
                new SelectListItem { Value = "Holanda 100 Sócalo", Text = "Holanda 100 Sócalo" },
                new SelectListItem { Value = "Holanda 100 Piso 5", Text = "Holanda 100 Piso 5" },
                new SelectListItem { Value = "Holanda 64", Text = "Holanda 64" },
                new SelectListItem { Value = "Sucursal Independencia", Text = "Sucursal Independencia" },
                new SelectListItem { Value = "Prilogic", Text = "Prilogic" },
            };
            }
        }

        public string DestinoSeleccionado { get; set; }


        public List<PRODUCTO> lista { get; set; }
        public string sumasolicitdada { get; set; }

        public List<ProductoSolicitud> lista2 { get; set; }
    }
}

BancoEstadoBodega/Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BancoEstadoBodega.Models;
using System.Data.Entity.Validation;
using System.Data.Entity.Infrastructure;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.IO;
using System.Xml;
using System.Configuration;
using System.Data.SqlClient;
using Microsoft.AspNet.Identity;
using System.Web.Security;
using System.Security.Claims;
using Microsoft.AspNet.Identity.Owin;
using System.Threading.Tasks;
using OfficeOpenXml;
using OfficeOpenXml.Style;
using System.Drawing;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using Microsoft.AspNet.Identity.EntityFramework;

namespace BancoEstadoBodega.Controllers
{
    [Authorize]
    public class SolicitudController : Controller
    {
        private LosHeroesEntities1 db = new LosHeroesEntities1();


        // GET: Solicitud
        public ActionResult Index()
        {

            var Solicitud = db.SolicitudPedido.Include(s => s.idSolicitud);
            return View();

        }

        //Obtiene los detalles de los productos y los muestra en el view Detalles
        public ViewResult Detalles(int id)
        {
            SolicitudPedido sp = db.SolicitudPedido.Find(id);
            return View(sp);
        }

        public ViewResult DetalleBodega(int id)
        {
            SolicitudPedido sp = db.SolicitudPedido.Find(id);
            return View(sp);
        }


        // Funcion que agrega los productos con imagen (ventana flotante) 
        //public ActionResult CrearSolicitud(int IdProducto)
        //{
        //    var details = db.PRODUCTO;
        //    //Hard coded for demo. You may replace it with data from db.
        //    return Json(details, JsonRequestBehavior.AllowGet);
        //}
        public ActionResult CrearSolicitud2()
        {
            var model = new SolicitudViewModel();
            /*if (!User.IsInRole("administradores"))
            {
                int cod = EnRol();
                model.PRODUCTO = db.PRODUCTO.Where(p => p.IDClienteFK == cod).OrderBy(p => p.Nombre).Select(p => new SelectListItem { Value = p.IDProducto.ToString(), Text = p.Nombre }).ToList();
            }
            else
            {
                model.PRODUCTO = db.PRODUCTO.OrderBy(p => p.Nombre).Select(p => new SelectListItem { Value = p.IDProducto.ToString(), Text = p.Nombre }).ToList();
            }*/
            model.PRODUCTO = db.PRODUCTO.OrderBy(p => p.Nombre).Select(p => new SelectListItem { Value = p.IDProducto.ToString(), Text = p.Nombre }).ToList();
            model.UserSoloVista = db.UserSoloVista.OrderBy(p => p.Nombre).Select(p => new SelectListItem { Value = p.Nombre.ToString(), Text = p.Nombre }).ToList();
            return View(model);
        }
        [HttpPost]

        public ActionResult CrearSolicitud2(SolicitudViewModel objeto)
        {
            try
            {
                string destino = " ";
                if (objeto.detalleDestino != null)
                {
                    destino = objeto.DestinoSeleccionado + " " + objeto.detalleDestino;
                }
                else
                {
                    destino = objeto.DestinoSeleccionado;
                }


                var Solicitud = new SolicitudPedido
                {
                    descripcion = objeto.numeroOC,
                    idTipoDespacho = 1,
                    destino = destino,
                    fechaSolicitud = DateTime.Now,
                    usuarioMandante = objeto.Comprador,
                    usuarioReceptor = objeto.Solicitante,
                    estado = "Solicitada",
                    correo = User.Identity.GetUserName(),
                    cod_estado = 1
                };

                db.SolicitudPedido.Add(Solicitud);
                db.SaveChanges();
                var idSol = Solicitud.idSolicitud;

                var lista = objeto.productosSeleccionados.ToList();

            
                if (lista.Count > 0)
                {
                    foreach (var item in lista)
                    {
                        var ProductoSolicitud = new ProductoSolicitud
                        {
                            idSolicitud = idSol,
                            idProducto = item.idProducto,
                            cantidad = item.cantidad,
                            NombreFK = item.NombreFK
                        };
                        var ProductoEnBodega = new ProductosEnBodega
                        {
                            idSolicitud = idSol,
                            idProducto = item.idProducto,
                            cantidad = item.cantidad,
                            NombreFK = item.NombreFK
                        };
                        db.ProductoSolicitud.Add(ProductoSolicitud);
                        db.ProductosEnBodega.Add(ProductoEnBodega);
                        db.SaveChanges();
                        PRODUCTO producto = db.PRODUCTO.Find(item.idProducto);
                        db.Entry(producto).State = EntityState.Modified;
                        var stock = producto.CantidadTotal;
                        producto.CantidadTotal = stock - item.cantidad;
                        db.SaveChanges();
                    }

                }
                /*-------------------------MENSAJE DE CORREO----------------------*/

                //Creamos un nuevo Objeto de mensaje
                System.Net.Mail.MailMessage mmsg = new System.Net.Mail.MailMessage();

                //Direccion de correo electronico a la que queremos enviar el mensaje
                //if (Request.IsAuthenticated)
                //{
                //mmsg.To.Add(User.Identity.GetUserName());
                //}
                mmsg.To.Add("lbasic@promomas.cl");
                //mmsg.To.Add("marco.molina@probag.cl");

                //Nota: La propiedad To es una colección que permite enviar el mensaje a más de un destinatario

                //Asunto
                mmsg.Subject = "Solicitud recepcionada";
                mmsg.SubjectEncoding = System.Text.Encoding.UTF8;

                //Direccion de correo electronico que queremos que reciba una copia del mensaje
                mmsg.Bcc.Add("marco.molina@probag.cl");
                //mmsg.Bcc.Add("marco.molina.hidalgo@gmail.cl");

                //if (Request.IsAuthenticated)
                //{
                    //mmsg.Bcc.Add(User.Identity.GetUserName());
                //}

                mmsg.To.Add("lbasic@promomas.cl");
                mmsg.Bcc.Add("yessyca@probag.cl");
                mmsg.Bcc.Add("facturacion@promomas.cl");
                //mmsg.To.Add("marco.molina@probag.cl");
                //if (Request.IsAuthenticated)
                //{
                //mmsg.Bcc.Add(User.Identity.GetUserName());
                //}

                //mmsg.Bcc.Add(user); //Opcional;

                //LoginViewModel model3;

                //Cuerpo del Mensaje
                DateTime fecha = DateTime.Now;
                string fech = fecha.ToString("dd/MM/yyyy");
         
                string descripción = "<div><p>Empresa: Los Heroes</p> </br><p>OC: " + Solicitud.descripcion + "</p></ br><p>Comprador: " + Solicitud.usuarioMandante + "</p></ br><p>Solicitante: " + Solicitud.usuarioReceptor + "</p><p>Destino: " + Solicitud.destino + "</p></div>";
                string tabla = "<table align='center' border='0' width='80%'><tr bgcolor='#70bbd9'><th>Código</th><th>Descripción</th><th>Cantidad Solicitada</th></tr>";
                string list = "";
                int largo = lista.Count;
                int contador = 0;
                if (largo > 0)
                {
                    foreach (var item in lista)
                    {
                        var productoAux = db.PRODUCTO.Find(item.idProducto);
                        contador = contador + 1;
                        list = list + "<tr bgcolor ='#e8e8e8'><td>" + productoAux.Codigo + "</td><td>" + productoAux.Nombre + "</td><td>" + item.cantidad + "</td></tr>";
                        if (contador == largo)
                        {
                            list = list + "</table>";
                        }
                    }
                }
                string footer = "<p align='center'> para ver más detalles de la solicitud <a href='http://losheroes.micatalogo.cl/Solicitud/Detalles/" + Solicitud.idSolicitud+"'>pinche aquí­</a></p>";
                mmsg.Body = descripción + "</br>" + tabla + list + footer;
                mmsg.BodyEncoding = System.Text.Encoding.UTF8;
                mmsg.IsBodyHtml = true; //Si no queremos que se envíe como HTML

                //Correo electronico desde la que enviamos el mensaje
                mmsg.From = new System.Net.Mail.MailAddress("solicitudes@promomas.cl");

                /*-------------------------CLIENTE DE CORREO----------------------*/

                //Creamos un objeto de cliente de correo
                System.Net.Mail.SmtpClient cliente = new System.Net.Mail.SmtpClient();

                //Hay que crear las credenciales del correo emisor
                cliente.Credentials = new System.Net.NetworkCredential("solicitudes@promomas.cl", "probag63");

                //Lo siguiente es obligatorio si enviamos el mensaje desde Gmail
                /*
                cliente.Port = 587;
                cliente.EnableSsl = true;
                */
                cliente.Host = "mail.promomas.cl"; //Para Gmail "smtp.gmail.com";

                /*-------------------------ENVIO DE CORREO----------------------*/

                try
                {
                    //Enviamos el mensaje      
                    cliente.Send(mmsg);
                }
                catch (System.Net.Mail.SmtpException ex)

BancoEstadoBodega/Views/Solicitud/AsignarProducto.cshtml
@model BancoEstadoBodega.Models.ProductoSolicitud

@{
    ViewBag.Title = "AsignarProducto";
}

<h2>Asignar Productos</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ProductoSolicitud</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.idSolicitud, "idSolicitud", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idSolicitud", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idSolicitud, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.idProducto, "idProducto", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("idProducto", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.idProducto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cantidad, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cantidad, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cantidad, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "SolicitudPedido")
</div>

BancoEstadoBodega/Views/Solicitud/CrearSolicitud.cshtml
@model BancoEstadoBodega.Models.ProductoViewModel
@{
    ViewBag.Title = "Creación de Solicitud";
}

<h2>Agregar Solicitud</h2>
<div>
    <form action="@Url.Action("CrearSolicitud", "Solicitud")" id="forma" enctype="multipart/form-data" method="post">
        
        <div class="modal-body">
            <div class="input-group">
                <span class="input-group-addon">Descripción</span>
                <input type="text" class="form-control" name="descripcion" placeholder="Descripción" maxlength="150" required>
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Tipo Despacho</span>
                @Html.DropDownList("idTipoDespacho", null, "Seleccione", htmlAttributes: new { @class = "form-control input-sm" })
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Destino</span>
                <input type="text" class="form-control" name="destino" placeholder="Destino" required>
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Area</span>
                @Html.DropDownList("idArea", null, "Seleccione", htmlAttributes: new { @class = "form-control input-sm" })
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Usuario Mandante</span>
                <input type="text" class="form-control" name="usuarioMandante" placeholder="Usuario Mandante" maxlength="100" required>
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Usuario Receptor</span>
                <input type="text" class="form-control" name="usuarioReceptor" placeholder="Usuario Receptor" required>
            </div>
            <br />
            <div class="input-group">
                <span class="input-group-addon">Observación</span>
                <input type="text" class="form-control" name="observacion" placeholder="Observación" required>
            </div>
            <br />
            <div class="input-group">
                <!--pendiente agregar productos a la tabla-->
                <input type="hidden" class="form-control" id="estado" name="estado" placeholder="Estado" value="" />

            </div>
            <div>

            </div>
            <div>
                <table id="tbProductos" class="table table-striped table-bordered">
                    <tr class="success">
                        <td width="75%" class="text-center">
                            Producto
                        </td>
                        <td width="25%" class="text-center">
                            Cantidad
                        </td>
                    </tr>
                    <tr class="success">
                        <td width="75%" class="text-center">
                            @Html.DropDownList("Productos", Model.PRODUCTO, "Seleccione...", htmlAttributes: new { @class = "form-control input-sm" })
                        </td>
                        <td class="text-center"><input type="number" id="cantidadMaxima"  min="0" placeholder="Seleccione Producto"></td>
                    </tr>
                </table>
                <br>
                <input type="button" id="add" value="Agregar Producto" class="bottom-right" onclick="agregar()">
                <input type="button" value="Eliminar" class="glyphicon-sort-by-attributes" onclick="borrarUltima()">
            </div>
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
            <button type="button" id="finish" class="btn btn-primary" onclick="validarForm()">Agregar Solicitud</button>
        </div>

    </form>

  
</div>

<asp:label id="lbl" runat="server" style="visibility:hidden"></asp:label>




<script type="text/javascript">
    $(document).ready(function () {
        $('#example').DataTable();
        $('[rel="popover"]').popover({
            container: 'body',
            html: true,
            content: function () {
                var clone = $($(this).data('popover-content')).clone(true).removeClass('hide');
                return clone;
            }
        }).click(function (e) {
            e.preventDefault();
        });
    });


    var contLin = 0;
    function agregar() {
        //var tr, td;
        if ($('#Productos').val() == 0) {
            alert('Por favor seleccione un producto');
        } else {
            if ($('#cantidadMaxima').val() == 0) {
                alert('El valor seleccionado no es valido o no posee stock');
            } else {
                var item = $('#Productos').val();//Se obtiene el id del producto
                var valor = $('#cantidadMaxima').val();
                tr = document.all.tbProductos.insertRow();
                td = tr.insertCell();
                //td.innerHTML = "@@"+ "Html.DropDownList('idProducto2', null, '', htmlAttributes: new { " +"@@" +  "class = 'form-control input-sm' })";
                //td.innerHTML = "<label id='lbl1" + contLin +"'>" + $('#idProducto').selected.text +"</label>";
                td.innerHTML = $("#Productos option:selected").text();//se agrega el nombre del producto
                td = tr.insertCell();
                td.innerHTML = $('#cantidadMaxima').val();
                contLin++;
                lbl.textContent = lbl.textContent + item + "v" + valor + ",";


                $("#estado").val(lbl.textContent);


            }

        }



    }
    function borrarUltima() {

        if (contLin >= 1) {
            ultima = document.all.tbProductos.rows.length - 1;
            document.all.tbProductos.deleteRow(ultima);
            contLin--;
            var prod = lbl.textContent.split(',');
            var count = prod.length;
            var cant = 0;
            var nuevos = '';
            while (cant < count - 2) {
                nuevos = nuevos + prod[cant] + ",";
                cant++;
            }
            lbl.textContent = nuevos;
            $("#estado").val(lbl.textContent);
        } else
        {
            alert('No hay mas elementos para eliminar en la lista');

        }
        
    }

    function validarForm()
    {
        if (contLin == 0) {
            alert('Debe agregar al menos un producto a la solicitud');
        } else
        {
            document.getElementById("forma").submit();
        }
        }
</script>

@*<script type="text/javascript">
    $(function () {

        $("[name='Productos']").change(function () {
            $("#cantidadMaxima").val($(this).val());

        });
    });

</script>*@

<script type="text/javascript">
    $(document).ready(function () {
        $(function () {
            $("[name='Productos']").change(function () {
                $("#cantidadMaxima").val("");
                var v = $(this).val();
                var url = "@Url.Action("StockMaximo","Solicitud")";
                $.getJSON(url, { id: v }, function (data) {

                    //$("#cantidadMaxima").val(data);
                    var max = data;
                    $("#cantidadMaxima").attr("placeholder", "Stock disponible: "+data);
                    $("#cantidadMaxima").attr("max", data);
                    $("#cantidadMaxima").val(data);
                    $("#cantidadMaxima").change(function () {
                        if ($(this).val() > max || $(this).val() < 0) {
                            alert('cantidad mayor al stock actual');
                            document.getElementById("add").disabled = true;
                        } else {
                            document.getElementById("add").disabled = false;
                        }
                    });
                });
            });
        });
    });

    
</script>

BancoEstadoBodega/Views/Solicitud/DetalleBodega.cshtml
@model BancoEstadoBodega.Models.SolicitudPedido
@{
    ViewBag.Title = "Detalles";
}

<h2>Detalles</h2>

<div>
    <h4>Solicitud de Pedido - Detalle</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            N° OC
        </dt>

        <dd>
            @Html.DisplayFor(model => model.descripcion)
        </dd>
        <dt>
            Destino
        </dt>

        <dd>
            @Html.DisplayFor(model => model.destino)
        </dd>

        <dt>
            Fecha de Solicitud
        </dt>

        <dd>
            @Html.DisplayFor(model => model.fechaSolicitud)
        </dd>
        

        <dt>
            Comprador
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioMandante)
        </dd>

        <dt>
            Solicitante
        </dt>

        <dd>
            @Html.DisplayFor(model => model.usuarioReceptor)
        </dd>
        
    </dl>





</div>

<div class="panel-body">
    <div class="table-responsive">
        <table class="table table-hover table-bordered">
            <thead>
                <tr>
                    <th>CODIGO</th>
                    <th>PRODUCTO</th>
                    <th>CANTIDAD EN BODEGA</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.ProductosEnBodega)
                {
                    if (@item.idProducto != 0)
                    {

                        {
                            <tr>
                                <td>
                                    @item.idSolicitud
                                </td>
                                <td>
                                    @item.PRODUCTO.Nombre
                                </td>
                                <td>
                                    @item.cantidad
                                </td>
                            </tr>
                        }

                    }

                }
            </tbody>
        </table>
    </div>
</div>

<p>
    @Html.ActionLink("Volver", "SolicitudPedido")
</p>

BancoEstadoBodega/Views/Solicitud/Principal.cshtml
@model BancoEstadoBodega.Models.SolicitudPedido

@{
    ViewBag.Title = "Principal";
    Layout = "~/Views/Administracion/Producto.cshtml";
}

<h2>Principal</h2>

BancoEstadoBodega/Views/Solicitud/ProductosSolicitud.cshtml
@model IEnumerable<BancoEstadoBodega.Models.ProductoSolicitud>

@{
    ViewBag.Title = "Productos Sin Despachar";
}

<h2>Productos Sin Despachar</h2>

<!-- Seccion que muestra la lista de productos -->
<div class="row">
    <div class="col-md-12">

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="glyphicon glyphicon-transfer" aria-hidden="true"></span> Lista de Productos</h3>
            </div>
            <div class="panel-body">
                <br />
                <div class="table-responsive">
                    <table id="example" class="table table-striped table-bordered" cellspacing="0">
                        <thead>
                            <tr class="success">
                                <th>N° OC</th>
                                <th>Nombre</th>
                                <th>Cantidad</th>
                                <th>Opciones</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                                <tr>
                                    <td> @item.SolicitudPedido.descripcion </td>
                                    <td> @item.PRODUCTO.Nombre </td>
                                    <td> @item.cantidad </td>
                                    <td class="text-center">
                                        @if (ViewContext.HttpContext.User.IsInRole("administradores"))
                                        {
                                            <a class="btn btn-success btn-xs" title="Editar" href='@Url.Action( "Confirmar", "Solicitud", new { idProducto = item.idProducto, idSolicitud = item.idSolicitud })'>
                                                <span class="glyphicon glyphicon-send"></span> Despachar
                                            </a>  
                                        }

                                    </td>
                                </tr>
                            }

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function () {
        $('#example').DataTable({
            "order": [[0, "desc"]]
        });
        $('[rel="popover"]').popover({
            container: 'body',
            html: true,
            content: function () {
                var clone = $($(this).data('popover-content')).clone(true).removeClass('hide');
                return clone;
            }
        }).click(function (e) {
            e.preventDefault();
        });
    });

</script>