BancoEstadoBodega/Models/CATEGORIA.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CATEGORIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CATEGORIA()
        {
            this.CATEGORIA1 = new HashSet<CATEGORIA>();
            this.PRODUCTO = new HashSet<PRODUCTO>();
        }
    
        public int IdCategoria { get; set; }
        public string Nombre { get; set; }
        public string Color { get; set; }
        public Nullable<int> IdCategoriaFK { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CATEGORIA> CATEGORIA1 { get; set; }
        public virtual CATEGORIA CATEGORIA2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
    }
}

BancoEstadoBodega/Models/PRODUCTO.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BancoEstadoBodega.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCTO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCTO()
        {
            this.ProductosEnBodega = new HashSet<ProductosEnBodega>();
            this.ProductoSolicitud = new HashSet<ProductoSolicitud>();
            this.PRODUCTOBODEGA = new HashSet<PRODUCTOBODEGA>();
        }
    
        public int IDProducto { get; set; }
        public string Codigo { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> IDCategoriaFK { get; set; }
        public Nullable<System.DateTime> FechaVencimiento { get; set; }
        public byte[] imagenProducto { get; set; }
        public string Posicion { get; set; }
        public Nullable<int> CantidadTotal { get; set; }
        public Nullable<int> UnidadesXCaja { get; set; }
        public Nullable<int> TotalCajas { get; set; }
        public Nullable<int> TotalSueltas { get; set; }
        public Nullable<int> IDClienteFK { get; set; }
        public string UrlImagen { get; set; }
        public Nullable<int> StockQl { get; set; }
        public Nullable<int> StockDÑ { get; set; }
        public byte[] foto { get; set; }
        public string Obs { get; set; }
        public Nullable<int> SueltasQL { get; set; }
        public Nullable<int> SueltasDÑ { get; set; }
        public Nullable<int> stock_ideal { get; set; }
        public Nullable<int> ProductoConLogo { get; set; }
        public Nullable<int> ProductoSinLogo { get; set; }
        public Nullable<int> pendiente { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> PrecioUni { get; set; }
        public string TiempoReposicion { get; set; }
        public string Packing { get; set; }
        public string Vencimiento { get; set; }
    
        public virtual CATEGORIA CATEGORIA { get; set; }
        public virtual CLIENTE CLIENTE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductosEnBodega> ProductosEnBodega { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductoSolicitud> ProductoSolicitud { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTOBODEGA> PRODUCTOBODEGA { get; set; }
    }
}

BancoEstadoBodega/Models/ProductoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using BancoEstadoBodega.Models;
using System.Web.Mvc;

namespace BancoEstadoBodega.Models
{
    public class ProductoViewModel
    {
        public List<SelectListItem> PRODUCTO { get; set; }
    }
}

BancoEstadoBodega/Controllers/AdministracionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BancoEstadoBodega.Models;
using System.Drawing;
using System.Drawing.Imaging;
using System.Data.Entity;
using Microsoft.Azure; // Namespace for CloudConfigurationManager
using Microsoft.WindowsAzure.Storage; // Namespace for CloudStorageAccount
using Microsoft.WindowsAzure.Storage.Blob; // Namespace for Blob storage type
using System.Net;
using System.Data;
using System.IO;
using System.Xml.Serialization;
using System.Collections;
using System.Data.Entity.Validation;

namespace BancoEstadoBodega.Controllers
{
    [Authorize]
    public class AdministracionController : Controller
    {

        private LosHeroesEntities1 db = new LosHeroesEntities1();
        // GET: Administracion  
        public ActionResult Index()
        {
            var productos = db.PRODUCTO.Include(m => m.IDClienteFK);
            return View();
        }

        //Convertir imagen
        public ActionResult convertirImagen(string codigo)
        {
            try
            {
                var imagenProducto = db.PRODUCTO.Where(x => x.Codigo == codigo).FirstOrDefault();

                return File(imagenProducto.imagenProducto, "image/jpeg");
            }
            catch (Exception ex)
            { }
            return null;
        }


        // GET: PRODUCTO/Create
        public ActionResult Create()
        {
            ViewBag.IDCategoriaFK = new SelectList(db.CATEGORIA, "IdCategoria", "Nombre");
            ViewBag.IDClienteFK = new SelectList(db.CLIENTE, "IDCliente", "Alias");
            return View();
        }

        // POST: PRODUCTOes/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IDProducto,Codigo,Nombre,UnidadesXCaja,CostoUnid,IDCategoriaFK,TotalCajas,TotalSueltas,FechaVencimiento,IDClienteFK,UrlImagen")] PRODUCTO pRODUCTO, HttpPostedFileBase imagenProducto)
        {
            if (imagenProducto != null && imagenProducto.ContentLength > 0)
            {
                byte[] imageData = null;
                using (var binaryReader = new BinaryReader(imagenProducto.InputStream))
                {
                    imageData = binaryReader.ReadBytes(imagenProducto.ContentLength);
                }
                //setear la imagen a la entidad que se creara
                pRODUCTO.imagenProducto = imageData;
            }

            if (ModelState.IsValid)
            {
                db.PRODUCTO.Add(pRODUCTO);
                db.SaveChanges();
                return RedirectToAction("Producto");
            }

            ViewBag.IDCategoriaFK = new SelectList(db.CATEGORIA, "IdCategoria", "Nombre", pRODUCTO.IDCategoriaFK);
            ViewBag.IDClienteFK = new SelectList(db.CLIENTE, "IDCliente", "Alias", pRODUCTO.IDClienteFK);
            return View(pRODUCTO);
        }



        #region CATEGORIA
        public ActionResult Categoria()
        {
            return View(/*db.CATEGORIA.ToList()*/);
        }

        [HttpPost]
        public ActionResult AgregarCategoria()
        {
            return View();
        }

        [HttpPost]
        public ActionResult ModificarCategoria()
        {
            return View();
        }

        [HttpPost]
        public ActionResult EliminarCategoria()
        {
            return View();
        }

        #endregion

        #region PRODUCTO
        public ActionResult Producto(int? IDEmpresa, int? IDCategoria)
        {
            //int codigo = EnRol();

            ViewBag.IDEmpresa = new SelectList(db.CLIENTE.ToList(), "IDCliente", "Alias", IDEmpresa);
            ViewBag.IDCategoria = new SelectList(db.CATEGORIA.ToList(), "IDCategoria", "Nombre", IDCategoria);
            ViewBag.IDCategoriaFK = ViewBag.IDCategoria;
            ViewBag.IDClienteFK = ViewBag.IDEmpresa;

            var modelo = new SolicitudViewModel();

            modelo.lista = db.PRODUCTO.ToList();
            modelo.lista2 = db.ProductoSolicitud.ToList();
            
            if (IDEmpresa != null)
            {
                modelo.lista = modelo.lista.Where(r => r.IDClienteFK == IDEmpresa).ToList();
            }
            if (IDCategoria != null)
            {
                modelo.lista = modelo.lista.Where(r => r.IDCategoriaFK == IDCategoria).ToList();
            }
            return View(modelo);
        }


        // Funcion que agrega los productos con imagen (ventana flotante) 
        public ActionResult AgregarProducto([Bind(Include = "IDProducto,Descripcion,Codigo,Nombre,stock_ideal,CostoUnid,Posicion,FechaVencimiento,IDCategoriaFK,CantidadTotal,pendiente,ProductoConLogo,ProductoSinLogo,PrecioUni,TiempoReposicion,Packing,Vencimiento")]PRODUCTO model, FormCollection collection, HttpPostedFileBase imagenProducto)
        {
            PRODUCTOBODEGA item = new PRODUCTOBODEGA();
            PRODUCTOBODEGA item2 = new PRODUCTOBODEGA();

            //item.BODEGA_IDBodega = 1;
            //model.PRODUCTOBODEGA.Add(item);

            //item2.Sueltas = Convert.ToInt32(collection["Bodega2Cajas"]);
            //item2.Cajas = Convert.ToInt32(collection["Bodega2Sueltas"]);
            //item2.BODEGA_IDBodega = 3;
            //model.PRODUCTOBODEGA.Add(item);
            //model.UrlImagen = model.Codigo + ".jpg";



            if (imagenProducto != null && imagenProducto.ContentLength > 0)
            {
                /*byte[] imageData = null;
                using (var binaryReader = new BinaryReader(imagenProducto.InputStream))
                {
                    imageData = binaryReader.ReadBytes(imagenProducto.ContentLength);
                }
                setear la imagen a la entidad que se creara
                model.imagenProducto = imageData;*/              
                string imgName = model.Codigo + ".jpg";//variable local que concatena el codigo del producto mas .jpg(imagen)
                model.UrlImagen = imgName;//texto concatenado es asignado al valor UrilImagen de la variable local model
                new BlobService().AddImgProducto(imagenProducto, imgName);//se activa la funcion addImgProducto de la clase BlobService
            }

            db.PRODUCTO.Add(model);
            db.SaveChanges();
            return RedirectToAction("Producto");
        }

        //Obtiene los detalles de los productos y los muestra en el view Detalles
        public ViewResult Detalles(int id)
        {
            PRODUCTO producto = db.PRODUCTO.Find(id);
            //if que asigna una imagen por defecto en caso que el campo UrlImagen de la tabla productos sea nulo
            if (producto.UrlImagen == null)
            {
                ViewBag.imagerurl = "https://pruebasmarco.blob.core.windows.net/prueba-fotos/noimage.jpg";
            }
            else
            {
                ViewBag.imagerurl = "https://pruebasmarco.blob.core.windows.net/losheroesblob/" + producto.Codigo + ".jpg";
            }
            return View(producto);
        }

        /*Obtiene la imagen asociada al producto y lo despliega en la grilla
        public ViewResult Producto(int id)
        {
            PRODUCTO producto = db.PRODUCTO.Find(id);
            ViewBag.imagerurl = "https://pruebasmarco.blob.core.windows.net/prueba-fotos/" + producto.Codigo + ".jpg";
            return ViewBag;
        }*/

        // GET: PRODUCTOes/Edit/5
        public ActionResult Editar(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            PRODUCTO pRODUCTO = db.PRODUCTO.Find(id);
            if (pRODUCTO == null)
            {
                return HttpNotFound();
            }
            ViewBag.IDCategoriaFK = new SelectList(db.CATEGORIA, "IdCategoria", "Nombre", pRODUCTO.IDCategoriaFK);
            if (pRODUCTO.UrlImagen == null)
            {
                ViewBag.imagerurl = "https://pruebasmarco.blob.core.windows.net/prueba-fotos/noimage.jpg";
            }
            else
            {
                ViewBag.imagerurl = "https://pruebasmarco.blob.core.windows.net/losheroesblob/" + pRODUCTO.Codigo + ".jpg";
            }

            ViewBag.IDClienteFK = new SelectList(db.CLIENTE, "IDCliente", "Alias", pRODUCTO.IDClienteFK);
            return View(pRODUCTO);
        }

        // POST: PRODUCTOes/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "IDProducto,Codigo,Nombre,UnidadesXCaja,StockQl,CantidadTotal,TotalCajas,TotalSueltas,SueltasQL,StockDÑ,SueltasDÑ,CostoUnid,Posicion,FechaVencimiento,stock_ideal,IDCategoriaFK,IDClienteFK,ProductoConLogo,ProductoSinLogo,pendiente,Descripcion,PrecioUni,TiempoReposicion,Packing,Vencimiento,Obs")] PRODUCTO pRODUCTO, HttpPostedFileBase imagenProducto)
        {
            string imgName = pRODUCTO.Codigo + ".jpg";//variable local que concatena el codigo del producto mas .jpg(imagen)
            if (pRODUCTO.UrlImagen == null)
            {
                pRODUCTO.UrlImagen = imgName;//texto concatenado es asignado al valor UrilImagen de la variable local model
                new BlobService().AddImgProducto(imagenProducto, imgName);//se activa la funcion addImgProducto de la clase BlobService
            }


            if (ModelState.IsValid)
            {
                db.Entry(pRODUCTO).State = EntityState.Modified;
                //pRODUCTO.TotalSueltas = pRODUCTO.SueltasDÑ.Value + pRODUCTO.SueltasQL.Value;

BancoEstadoBodega/Views/Administracion/Create.cshtml
@model BancoEstadoBodega.Models.PRODUCTO

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm("Create", "Administracion", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
  
    <div class="form-horizontal">
        <h4>PRODUCTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Codigo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Codigo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Codigo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombre, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UnidadesXCaja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UnidadesXCaja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UnidadesXCaja, "", new { @class = "text-danger" })
            </div>
        </div>

     

        <div class="form-group">
            @Html.LabelFor(model => model.IDCategoriaFK, "IDCategoriaFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDCategoriaFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDCategoriaFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalCajas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalCajas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalCajas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TotalSueltas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TotalSueltas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TotalSueltas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaVencimiento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaVencimiento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaVencimiento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IDClienteFK, "IDClienteFK", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IDClienteFK", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.IDClienteFK, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UrlImagen, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UrlImagen, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UrlImagen, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.imagenProducto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imagenProducto" />
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.foto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" id="foto" name="foto" class="form-control">
                
            </div>
        </div>

    
       


            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BancoEstadoBodega/Views/Administracion/EditarImagen.cshtml
@model BancoEstadoBodega.Models.PRODUCTO

@{
    ViewBag.Title = "Actualizar Imagen";
}

<h2>Editar</h2>

@using (Html.BeginForm("EditarImagen", "Administracion", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>PRODUCTO</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.IDProducto)


        <div class="form-group">
            @Html.Label("Imagen Actual", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <img width="250" height="250" src="@ViewBag.imagerurl" alt="Producto" class="imagine" />
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Cambiar Imagen", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="imagenProducto" class="input-file" tam="300" />
            </div>
        </div>

      

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>

        El tamaño máximo permitido es de 300Kb, si la imagen excede, puede redimencionarla en <a target="_blank" href="http://webresizer.com/resizer/">este link.</a>

    </div>
}

<script type="text/javascript">
    $(document).ready(function () {
        /* Valida el tamaño maximo de un archivo adjunto */
        $('.input-file').change(function () {
            var sizeByte = this.files[0].size;
            var siezekiloByte = parseInt(sizeByte / 1024);

            if (siezekiloByte > $(this).attr('tam')) {
                alert('El tamaño supera el limite permitido (300kb)');
                $(this).val('');
            }
        });
    });
</script>

BancoEstadoBodega/Views/Administracion/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"> <span class="glyphicon glyphicon-th" aria-hidden="true"></span> Opciones de Modificación</h3>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-md-4">
                        <div class="bs-callout bs-callout-danger"> 
                            <h3>Categoria</h3>
                            <p>Calificación, selecccion y organización de los productos.</p>
                            <p class="text-right"><a href="../../Administracion/Categoria"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Ingresar</a></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bs-callout bs-callout-warning">
                            <h3>Productos</h3> 
                            <p>Nombre de productos con sus caracteristicas y forma de almacenaje.</p>
                            <p class="text-right"><a href="../../Administracion/Producto"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Ingresar</a></p>
                        </div>
                    </div>
                    <div class="col-md-4">  
                        <div class="bs-callout bs-callout-info">
                            <h3>Usuarios</h3> 
                            <p>Administracion de datos y roles de los usuarios del sistema</p>
                            <p class="text-right"><a href="#"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Ingresar</a></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bs-callout bs-callout-danger">
                            <h3>Region/Ciudad/Comuna</h3>
                            <p>Base de datos de Regiones con sus respectivas Ciudades y Comunas.</p>
                            <p class="text-right"><a href="#"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Ingresar</a></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bs-callout bs-callout-warning">
                            <h3>Clientes</h3>
                            <p>Cada cliente con sus datos obligatorios para contacto y SII.</p>
                            <p class="text-right"><a href="#"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Ingresar</a></p>
                        </div>
                    </div>
                    <div class="col-md-4">
                        <div class="bs-callout bs-callout-info">
                            <h3>Lugares de Despacho</h3>
                            <p>Base de datos de los despacho de cada uno de los Clientes.</p>
                            <p class="text-right"><a href="#"><span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span> Ingresar</a></p>
                        </div>
                    </div>
                    </div>
            </div>
        </div>

    </div>
</div>